import Head from "next/head";
import Image from "next/image";
// import { Inter } from 'next/font/google'
import styles from "@/styles/Home.module.css";
import { Box, Typography } from "@mui/material";
import Header from "@/components/UI/Header";
import Hero from "@/components/UI/Homepage/Hero";
import About from "@/components/UI/Homepage/About";
import Services from "@/components/UI/Homepage/Services";
import ServicesTwo from "@/components/UI/Homepage/ServicesTwo";
import Footer from "@/components/UI/Homepage/Footer";

// const inter = Inter({ subsets: ['latin'] })

function Department() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}

      <Hero />
      <About />
      <Services />
      <ServicesTwo />
      <Footer />
    </>
  );
}

export default Department;
