import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import HeaderUser from "@/components/UI/HeaderUser";
import { Box, Typography, Container } from "@mui/material";
import Hero from "../components/UI/Homepage/Hero";
import About from "@/components/UI/Homepage/About";
import Services from "@/components/UI/Homepage/Services";
import ServicesTwo from "@/components/UI/Homepage/ServicesTwo";
import Footer from "@/components/UI/Homepage/Footer";
import { useEffect } from "react";
import { useRouter } from "next/router";

import { AES } from "crypto-js";
import CryptoJS from "crypto-js";
import Login from "./login";
import withUserCheck from "../../utils/withUserCheck";

import Cookies from "js-cookie";

function Home() {
	const route = useRouter();

	return (
		<>
			<Login />

			{/* <Head>
        <title>Him Access</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderUser />


      <Hero />
      <About />
      <Services />
      <ServicesTwo />
      <Footer /> */}
		</>
	);
}

export default Home;

// export default Home;
